--REPORTE DE FACTURAS SIN CANCELAR
SELECT
FACTURA,
FECHA,
CLIENTE,
EXENTO,
GRAVADO,
IMPUESTO,
TOTAL
FROM
FACTURACION_MANUAL
WHERE
TIPO IS NOT NULL
AND FECHA
BETWEEN
'2005-01-01' AND '2005-05-01'
AND FECHACANCELACION IS NULL
ORDER BY CLIENTE ASC