--TOTALES FACTURAS SIN CANCELAR
SELECT
SUM(EXENTO) AS TOTALEXENTO,
SUM(GRAVADO) AS TOTALGRAVADO,
SUM(IMPUESTO) AS TOTALIMPUESTO,
SUM(TOTAL) AS GRANTOTAL
FROM
FACTURACION_MANUAL
WHERE
TIPO IS NOT NULL
AND FECHA
BETWEEN
'2005-01-01' AND '2005-02-01'
AND FECHACANCELACION IS NULL
